
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: smart_ai_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smart-ai-hub
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smart-ai-hub
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - smart-ai-hub
    depends_on:
      - api-gateway
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    build: ./packages/api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    networks:
      - smart-ai-hub
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      core-service:
        condition: service_healthy
      mcp-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  auth-service:
    build: ./packages/auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=secret
      - OAUTH_CLIENT_ID=client_id
      - OAUTH_CLIENT_SECRET=client_secret
      - REDIS_URL=redis://redis:6379
    networks:
      - smart-ai-hub
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  core-service:
    build: ./packages/core-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/smart_ai_hub
      - REDIS_URL=redis://redis:6379
    networks:
      - smart-ai-hub
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mcp-server:
    build: ./packages/mcp-server
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    networks:
      - smart-ai-hub
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  notification-service:
    build: ./packages/notification-service
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    networks:
      - smart-ai-hub
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    build: ./packages/frontend
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:80
    networks:
      - smart-ai-hub
    depends_on:
      nginx:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  smart-ai-hub:
    driver: bridge