server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Auth Service Logs
  - job_name: auth-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth-service
          __path__: /var/log/auth-service/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            message: message
            userId: userId
            requestId: requestId
            duration: duration
            timestamp: timestamp
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          userId:

  # Core Service Logs
  - job_name: core-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: core-service
          __path__: /var/log/core-service/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            message: message
            userId: userId
            requestId: requestId
            duration: duration
            timestamp: timestamp
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          userId:

  # MCP Server Logs
  - job_name: mcp-server
    static_configs:
      - targets:
          - localhost
        labels:
          job: mcp-server
          __path__: /var/log/mcp-server/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            message: message
            userId: userId
            requestId: requestId
            duration: duration
            timestamp: timestamp
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          userId:

  # Analytics Service Logs
  - job_name: analytics-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: analytics-service
          __path__: /var/log/analytics-service/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            message: message
            userId: userId
            requestId: requestId
            duration: duration
            timestamp: timestamp
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          userId:

  # Webhook Service Logs
  - job_name: webhook-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: webhook-service
          __path__: /var/log/webhook-service/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            message: message
            userId: userId
            requestId: requestId
            duration: duration
            timestamp: timestamp
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          userId:

  # API Gateway Logs
  - job_name: api-gateway
    static_configs:
      - targets:
          - localhost
        labels:
          job: api-gateway
          __path__: /var/log/api-gateway/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            message: message
            userId: userId
            requestId: requestId
            duration: duration
            timestamp: timestamp
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          userId:

  # System Logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\w+)\s+(?P<service>[^\[]+)\[(?P<pid>\d+)\]:\s*(?P<message>.*)'
      - timestamp:
          source: timestamp
          format: 'Jan 02 15:04:05'
      - labels:
          service:
          hostname:

  # Docker Container Logs
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        port: 80
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
        replacement: '$1'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            message: message
            userId: userId
            requestId: requestId
            duration: duration
            timestamp: timestamp
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          userId: