global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@smart-ai-hub.com'
  smtp_require_tls: false

# Email templates
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'
  - match:
      severity: info
    receiver: 'info-alerts'

# Receivers configuration
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://webhook-service:3005/internal/alerts'
    send_resolved: true
    http_config:
      basic_auth:
        username: 'alertmanager'
        password: 'alertmanager_password'

- name: 'critical-alerts'
  email_configs:
  - to: 'admin@smart-ai-hub.com,ops@smart-ai-hub.com'
    subject: '[CRITICAL] Smart AI Hub Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Service: {{ .Labels.service }}
      Time: {{ .StartsAt }}
      {{ end }}
    send_resolved: true

- name: 'warning-alerts'
  email_configs:
  - to: 'ops@smart-ai-hub.com'
    subject: '[WARNING] Smart AI Hub Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Service: {{ .Labels.service }}
      Time: {{ .StartsAt }}
      {{ end }}
    send_resolved: true

- name: 'info-alerts'
  email_configs:
  - to: 'dev@smart-ai-hub.com'
    subject: '[INFO] Smart AI Hub Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Service: {{ .Labels.service }}
      Time: {{ .StartsAt }}
      {{ end }}
    send_resolved: true

# Inhibition rules
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']

- source_match:
    severity: 'warning'
  target_match:
    severity: 'info'
  equal: ['alertname', 'cluster', 'service']